# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIView.ui'
#
# Created: Tue Apr 28 07:42:45 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UIView(object):
    def setupUi(self, UIView):
        UIView.setObjectName(_fromUtf8("UIView"))
        UIView.resize(685, 565)
        font = QtGui.QFont()
        font.setPointSize(10)
        UIView.setFont(font)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(UIView)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pagesMain = QtGui.QStackedWidget(UIView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.pagesMain.sizePolicy().hasHeightForWidth())
        self.pagesMain.setSizePolicy(sizePolicy)
        self.pagesMain.setObjectName(_fromUtf8("pagesMain"))
        self.StartPage = QtGui.QWidget()
        self.StartPage.setObjectName(_fromUtf8("StartPage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.StartPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblWelcome_Title = QtGui.QLabel(self.StartPage)
        font = QtGui.QFont()
        font.setKerning(False)
        self.lblWelcome_Title.setFont(font)
        self.lblWelcome_Title.setObjectName(_fromUtf8("lblWelcome_Title"))
        self.horizontalLayout_4.addWidget(self.lblWelcome_Title)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.StartPage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 193, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.lblWelcome_Message = QtGui.QLabel(self.StartPage)
        self.lblWelcome_Message.setObjectName(_fromUtf8("lblWelcome_Message"))
        self.verticalLayout.addWidget(self.lblWelcome_Message)
        spacerItem2 = QtGui.QSpacerItem(20, 194, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.cmdStep0_Start = QtGui.QCommandLinkButton(self.StartPage)
        self.cmdStep0_Start.setMaximumSize(QtCore.QSize(100, 50))
        self.cmdStep0_Start.setAutoDefault(True)
        self.cmdStep0_Start.setDefault(False)
        self.cmdStep0_Start.setObjectName(_fromUtf8("cmdStep0_Start"))
        self.horizontalLayout_3.addWidget(self.cmdStep0_Start)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pagesMain.addWidget(self.StartPage)
        self.pageStep1 = QtGui.QWidget()
        self.pageStep1.setObjectName(_fromUtf8("pageStep1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageStep1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblStep1_Title = QtGui.QLabel(self.pageStep1)
        self.lblStep1_Title.setObjectName(_fromUtf8("lblStep1_Title"))
        self.horizontalLayout_5.addWidget(self.lblStep1_Title)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line_2 = QtGui.QFrame(self.pageStep1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        spacerItem5 = QtGui.QSpacerItem(20, 158, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem6 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.frmLayoutStep1 = QtGui.QFormLayout()
        self.frmLayoutStep1.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.frmLayoutStep1.setRowWrapPolicy(QtGui.QFormLayout.DontWrapRows)
        self.frmLayoutStep1.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frmLayoutStep1.setObjectName(_fromUtf8("frmLayoutStep1"))
        self.lblStep1_InputFile = QtGui.QLabel(self.pageStep1)
        self.lblStep1_InputFile.setMargin(5)
        self.lblStep1_InputFile.setObjectName(_fromUtf8("lblStep1_InputFile"))
        self.frmLayoutStep1.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblStep1_InputFile)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditStep1_InputFilename = QtGui.QLineEdit(self.pageStep1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditStep1_InputFilename.sizePolicy().hasHeightForWidth())
        self.lineEditStep1_InputFilename.setSizePolicy(sizePolicy)
        self.lineEditStep1_InputFilename.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEditStep1_InputFilename.setReadOnly(True)
        self.lineEditStep1_InputFilename.setObjectName(_fromUtf8("lineEditStep1_InputFilename"))
        self.horizontalLayout.addWidget(self.lineEditStep1_InputFilename)
        self.btnStep1_InputFile = QtGui.QPushButton(self.pageStep1)
        self.btnStep1_InputFile.setDefault(False)
        self.btnStep1_InputFile.setObjectName(_fromUtf8("btnStep1_InputFile"))
        self.horizontalLayout.addWidget(self.btnStep1_InputFile)
        self.frmLayoutStep1.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.lblStep1_InputFormat = QtGui.QLabel(self.pageStep1)
        self.lblStep1_InputFormat.setMargin(5)
        self.lblStep1_InputFormat.setObjectName(_fromUtf8("lblStep1_InputFormat"))
        self.frmLayoutStep1.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblStep1_InputFormat)
        self.lblStep1_OutputFormat = QtGui.QLabel(self.pageStep1)
        self.lblStep1_OutputFormat.setMargin(5)
        self.lblStep1_OutputFormat.setObjectName(_fromUtf8("lblStep1_OutputFormat"))
        self.frmLayoutStep1.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblStep1_OutputFormat)
        self.chkStep1_ExcelExtendedVersion = QtGui.QCheckBox(self.pageStep1)
        self.chkStep1_ExcelExtendedVersion.setEnabled(False)
        self.chkStep1_ExcelExtendedVersion.setObjectName(_fromUtf8("chkStep1_ExcelExtendedVersion"))
        self.frmLayoutStep1.setWidget(3, QtGui.QFormLayout.FieldRole, self.chkStep1_ExcelExtendedVersion)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.ddlStep1_InputFormat = QtGui.QComboBox(self.pageStep1)
        self.ddlStep1_InputFormat.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ddlStep1_InputFormat.sizePolicy().hasHeightForWidth())
        self.ddlStep1_InputFormat.setSizePolicy(sizePolicy)
        self.ddlStep1_InputFormat.setMinimumSize(QtCore.QSize(100, 0))
        self.ddlStep1_InputFormat.setObjectName(_fromUtf8("ddlStep1_InputFormat"))
        self.horizontalLayout_21.addWidget(self.ddlStep1_InputFormat)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.frmLayoutStep1.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.ddlStep1_OutputFormat = QtGui.QComboBox(self.pageStep1)
        self.ddlStep1_OutputFormat.setEnabled(False)
        self.ddlStep1_OutputFormat.setMinimumSize(QtCore.QSize(100, 0))
        self.ddlStep1_OutputFormat.setObjectName(_fromUtf8("ddlStep1_OutputFormat"))
        self.horizontalLayout_22.addWidget(self.ddlStep1_OutputFormat)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.frmLayoutStep1.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_22)
        self.horizontalLayout_7.addLayout(self.frmLayoutStep1)
        spacerItem9 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem10 = QtGui.QSpacerItem(20, 160, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.cmdStep1_Next = QtGui.QCommandLinkButton(self.pageStep1)
        self.cmdStep1_Next.setEnabled(False)
        self.cmdStep1_Next.setMaximumSize(QtCore.QSize(100, 50))
        self.cmdStep1_Next.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmdStep1_Next.setObjectName(_fromUtf8("cmdStep1_Next"))
        self.horizontalLayout_6.addWidget(self.cmdStep1_Next)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.pagesMain.addWidget(self.pageStep1)
        self.pageStep2 = QtGui.QWidget()
        self.pageStep2.setObjectName(_fromUtf8("pageStep2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pageStep2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lblStep2_Title = QtGui.QLabel(self.pageStep2)
        self.lblStep2_Title.setObjectName(_fromUtf8("lblStep2_Title"))
        self.horizontalLayout_8.addWidget(self.lblStep2_Title)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.line_3 = QtGui.QFrame(self.pageStep2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_7.addWidget(self.line_3)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.listStep2_ChosenVisualisations = QtGui.QListWidget(self.pageStep2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listStep2_ChosenVisualisations.setFont(font)
        self.listStep2_ChosenVisualisations.setSpacing(0)
        self.listStep2_ChosenVisualisations.setObjectName(_fromUtf8("listStep2_ChosenVisualisations"))
        self.verticalLayout_4.addWidget(self.listStep2_ChosenVisualisations)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btnStep2_ImportSettings = QtGui.QPushButton(self.pageStep2)
        self.btnStep2_ImportSettings.setObjectName(_fromUtf8("btnStep2_ImportSettings"))
        self.horizontalLayout_14.addWidget(self.btnStep2_ImportSettings)
        self.btnStep2_ExportSettings = QtGui.QPushButton(self.pageStep2)
        self.btnStep2_ExportSettings.setObjectName(_fromUtf8("btnStep2_ExportSettings"))
        self.horizontalLayout_14.addWidget(self.btnStep2_ExportSettings)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_18.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.ddlStep2_VisualisationType = Custom_QComboBox(self.pageStep2)
        self.ddlStep2_VisualisationType.setObjectName(_fromUtf8("ddlStep2_VisualisationType"))
        self.horizontalLayout_11.addWidget(self.ddlStep2_VisualisationType)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.grpbxStep2_VisualisationDescription = QtGui.QGroupBox(self.pageStep2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpbxStep2_VisualisationDescription.sizePolicy().hasHeightForWidth())
        self.grpbxStep2_VisualisationDescription.setSizePolicy(sizePolicy)
        self.grpbxStep2_VisualisationDescription.setMinimumSize(QtCore.QSize(0, 100))
        self.grpbxStep2_VisualisationDescription.setObjectName(_fromUtf8("grpbxStep2_VisualisationDescription"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.grpbxStep2_VisualisationDescription)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lblStep2_VisualisationDescription = QtGui.QLabel(self.grpbxStep2_VisualisationDescription)
        self.lblStep2_VisualisationDescription.setEnabled(False)
        self.lblStep2_VisualisationDescription.setObjectName(_fromUtf8("lblStep2_VisualisationDescription"))
        self.verticalLayout_9.addWidget(self.lblStep2_VisualisationDescription)
        self.verticalLayout_3.addWidget(self.grpbxStep2_VisualisationDescription)
        self.grpbxStep2_VisualisationParameters = QtGui.QGroupBox(self.pageStep2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpbxStep2_VisualisationParameters.sizePolicy().hasHeightForWidth())
        self.grpbxStep2_VisualisationParameters.setSizePolicy(sizePolicy)
        self.grpbxStep2_VisualisationParameters.setMinimumSize(QtCore.QSize(350, 200))
        self.grpbxStep2_VisualisationParameters.setObjectName(_fromUtf8("grpbxStep2_VisualisationParameters"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.grpbxStep2_VisualisationParameters)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lblStep2_Param_NoParams = QtGui.QLabel(self.grpbxStep2_VisualisationParameters)
        self.lblStep2_Param_NoParams.setEnabled(False)
        self.lblStep2_Param_NoParams.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStep2_Param_NoParams.setObjectName(_fromUtf8("lblStep2_Param_NoParams"))
        self.verticalLayout_10.addWidget(self.lblStep2_Param_NoParams)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblStep2_Param_LevelOfDetail = QtGui.QLabel(self.grpbxStep2_VisualisationParameters)
        self.lblStep2_Param_LevelOfDetail.setMargin(3)
        self.lblStep2_Param_LevelOfDetail.setObjectName(_fromUtf8("lblStep2_Param_LevelOfDetail"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblStep2_Param_LevelOfDetail)
        self.ddlStep2_Param_LevelOfDetail = QtGui.QComboBox(self.grpbxStep2_VisualisationParameters)
        self.ddlStep2_Param_LevelOfDetail.setObjectName(_fromUtf8("ddlStep2_Param_LevelOfDetail"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ddlStep2_Param_LevelOfDetail)
        self.chkStep2_Param_RelativeValues = QtGui.QCheckBox(self.grpbxStep2_VisualisationParameters)
        self.chkStep2_Param_RelativeValues.setObjectName(_fromUtf8("chkStep2_Param_RelativeValues"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.chkStep2_Param_RelativeValues)
        self.chkStep2_Param_AddThreshold = QtGui.QCheckBox(self.grpbxStep2_VisualisationParameters)
        self.chkStep2_Param_AddThreshold.setObjectName(_fromUtf8("chkStep2_Param_AddThreshold"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.chkStep2_Param_AddThreshold)
        self.lblStep2_Param_StartingThreshold = QtGui.QLabel(self.grpbxStep2_VisualisationParameters)
        self.lblStep2_Param_StartingThreshold.setMargin(3)
        self.lblStep2_Param_StartingThreshold.setObjectName(_fromUtf8("lblStep2_Param_StartingThreshold"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblStep2_Param_StartingThreshold)
        self.dblspnbxStep2_Param_StartThresholdValue = QtGui.QDoubleSpinBox(self.grpbxStep2_VisualisationParameters)
        self.dblspnbxStep2_Param_StartThresholdValue.setObjectName(_fromUtf8("dblspnbxStep2_Param_StartThresholdValue"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dblspnbxStep2_Param_StartThresholdValue)
        self.lblStep2_Param_EndingThreshold = QtGui.QLabel(self.grpbxStep2_VisualisationParameters)
        self.lblStep2_Param_EndingThreshold.setMargin(3)
        self.lblStep2_Param_EndingThreshold.setObjectName(_fromUtf8("lblStep2_Param_EndingThreshold"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblStep2_Param_EndingThreshold)
        self.dblspnbxStep2_Param_EndThresholdValue = QtGui.QDoubleSpinBox(self.grpbxStep2_VisualisationParameters)
        self.dblspnbxStep2_Param_EndThresholdValue.setObjectName(_fromUtf8("dblspnbxStep2_Param_EndThresholdValue"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.dblspnbxStep2_Param_EndThresholdValue)
        self.verticalLayout_10.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.grpbxStep2_VisualisationParameters)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.lblStep2_ParamsSaved = QtGui.QLabel(self.pageStep2)
        self.lblStep2_ParamsSaved.setEnabled(False)
        self.lblStep2_ParamsSaved.setObjectName(_fromUtf8("lblStep2_ParamsSaved"))
        self.horizontalLayout_13.addWidget(self.lblStep2_ParamsSaved)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.btnStep2_AddVisualisation = QtGui.QPushButton(self.pageStep2)
        self.btnStep2_AddVisualisation.setObjectName(_fromUtf8("btnStep2_AddVisualisation"))
        self.horizontalLayout_10.addWidget(self.btnStep2_AddVisualisation)
        self.btnStep2_DeleteVisualisation = QtGui.QPushButton(self.pageStep2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnStep2_DeleteVisualisation.setFont(font)
        self.btnStep2_DeleteVisualisation.setObjectName(_fromUtf8("btnStep2_DeleteVisualisation"))
        self.horizontalLayout_10.addWidget(self.btnStep2_DeleteVisualisation)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.cmdStep2_Convert = QtGui.QCommandLinkButton(self.pageStep2)
        self.cmdStep2_Convert.setMaximumSize(QtCore.QSize(100, 50))
        self.cmdStep2_Convert.setObjectName(_fromUtf8("cmdStep2_Convert"))
        self.horizontalLayout_12.addWidget(self.cmdStep2_Convert)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_18.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.pagesMain.addWidget(self.pageStep2)
        self.pageConverting = QtGui.QWidget()
        self.pageConverting.setObjectName(_fromUtf8("pageConverting"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pageConverting)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.lblConverting_Title = QtGui.QLabel(self.pageConverting)
        self.lblConverting_Title.setObjectName(_fromUtf8("lblConverting_Title"))
        self.horizontalLayout_15.addWidget(self.lblConverting_Title)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.line_4 = QtGui.QFrame(self.pageConverting)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_5.addWidget(self.line_4)
        spacerItem17 = QtGui.QSpacerItem(20, 142, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.lblConverting_Message = QtGui.QLabel(self.pageConverting)
        self.lblConverting_Message.setObjectName(_fromUtf8("lblConverting_Message"))
        self.verticalLayout_5.addWidget(self.lblConverting_Message)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem18)
        self.lblConverting_WaitingSpinner = QtGui.QLabel(self.pageConverting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConverting_WaitingSpinner.sizePolicy().hasHeightForWidth())
        self.lblConverting_WaitingSpinner.setSizePolicy(sizePolicy)
        self.lblConverting_WaitingSpinner.setMinimumSize(QtCore.QSize(100, 100))
        self.lblConverting_WaitingSpinner.setMaximumSize(QtCore.QSize(100, 100))
        self.lblConverting_WaitingSpinner.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConverting_WaitingSpinner.setObjectName(_fromUtf8("lblConverting_WaitingSpinner"))
        self.horizontalLayout_20.addWidget(self.lblConverting_WaitingSpinner)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem19)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        spacerItem20 = QtGui.QSpacerItem(20, 142, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.pagesMain.addWidget(self.pageConverting)
        self.pageConvertingError = QtGui.QWidget()
        self.pageConvertingError.setObjectName(_fromUtf8("pageConvertingError"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pageConvertingError)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.lblConvertingError_Title = QtGui.QLabel(self.pageConvertingError)
        self.lblConvertingError_Title.setObjectName(_fromUtf8("lblConvertingError_Title"))
        self.horizontalLayout_19.addWidget(self.lblConvertingError_Title)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.line_6 = QtGui.QFrame(self.pageConvertingError)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_8.addWidget(self.line_6)
        self.textEdit_errorMessagebox = QtGui.QTextEdit(self.pageConvertingError)
        self.textEdit_errorMessagebox.setObjectName(_fromUtf8("textEdit_errorMessagebox"))
        self.verticalLayout_8.addWidget(self.textEdit_errorMessagebox)
        self.pagesMain.addWidget(self.pageConvertingError)
        self.pageFinished = QtGui.QWidget()
        self.pageFinished.setObjectName(_fromUtf8("pageFinished"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pageFinished)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.lblFinished_Title = QtGui.QLabel(self.pageFinished)
        self.lblFinished_Title.setObjectName(_fromUtf8("lblFinished_Title"))
        self.horizontalLayout_16.addWidget(self.lblFinished_Title)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.line_5 = QtGui.QFrame(self.pageFinished)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_6.addWidget(self.line_5)
        spacerItem23 = QtGui.QSpacerItem(20, 163, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem23)
        self.lblFinished_Message = QtGui.QLabel(self.pageFinished)
        self.lblFinished_Message.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFinished_Message.setMargin(15)
        self.lblFinished_Message.setObjectName(_fromUtf8("lblFinished_Message"))
        self.verticalLayout_6.addWidget(self.lblFinished_Message)
        self.lblFinished_OutputFilename = QtGui.QLabel(self.pageFinished)
        self.lblFinished_OutputFilename.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFinished_OutputFilename.setMargin(5)
        self.lblFinished_OutputFilename.setObjectName(_fromUtf8("lblFinished_OutputFilename"))
        self.verticalLayout_6.addWidget(self.lblFinished_OutputFilename)
        spacerItem24 = QtGui.QSpacerItem(20, 162, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem24)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem25)
        self.cmdFinished_End = QtGui.QCommandLinkButton(self.pageFinished)
        self.cmdFinished_End.setMaximumSize(QtCore.QSize(100, 50))
        self.cmdFinished_End.setDefault(False)
        self.cmdFinished_End.setObjectName(_fromUtf8("cmdFinished_End"))
        self.horizontalLayout_17.addWidget(self.cmdFinished_End)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.pagesMain.addWidget(self.pageFinished)
        self.horizontalLayout_2.addWidget(self.pagesMain)

        self.retranslateUi(UIView)
        self.pagesMain.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(UIView)
        UIView.setTabOrder(self.cmdStep0_Start, self.btnStep1_InputFile)
        UIView.setTabOrder(self.btnStep1_InputFile, self.ddlStep1_InputFormat)
        UIView.setTabOrder(self.ddlStep1_InputFormat, self.ddlStep1_OutputFormat)
        UIView.setTabOrder(self.ddlStep1_OutputFormat, self.chkStep1_ExcelExtendedVersion)
        UIView.setTabOrder(self.chkStep1_ExcelExtendedVersion, self.cmdStep1_Next)
        UIView.setTabOrder(self.cmdStep1_Next, self.ddlStep2_VisualisationType)
        UIView.setTabOrder(self.ddlStep2_VisualisationType, self.ddlStep2_Param_LevelOfDetail)
        UIView.setTabOrder(self.ddlStep2_Param_LevelOfDetail, self.chkStep2_Param_RelativeValues)
        UIView.setTabOrder(self.chkStep2_Param_RelativeValues, self.chkStep2_Param_AddThreshold)
        UIView.setTabOrder(self.chkStep2_Param_AddThreshold, self.dblspnbxStep2_Param_StartThresholdValue)
        UIView.setTabOrder(self.dblspnbxStep2_Param_StartThresholdValue, self.dblspnbxStep2_Param_EndThresholdValue)
        UIView.setTabOrder(self.dblspnbxStep2_Param_EndThresholdValue, self.btnStep2_AddVisualisation)
        UIView.setTabOrder(self.btnStep2_AddVisualisation, self.btnStep2_DeleteVisualisation)
        UIView.setTabOrder(self.btnStep2_DeleteVisualisation, self.btnStep2_ImportSettings)
        UIView.setTabOrder(self.btnStep2_ImportSettings, self.btnStep2_ExportSettings)
        UIView.setTabOrder(self.btnStep2_ExportSettings, self.cmdStep2_Convert)
        UIView.setTabOrder(self.cmdStep2_Convert, self.textEdit_errorMessagebox)
        UIView.setTabOrder(self.textEdit_errorMessagebox, self.cmdFinished_End)
        UIView.setTabOrder(self.cmdFinished_End, self.listStep2_ChosenVisualisations)
        UIView.setTabOrder(self.listStep2_ChosenVisualisations, self.lineEditStep1_InputFilename)

    def retranslateUi(self, UIView):
        UIView.setWindowTitle(_translate("UIView", "PMConverter", None))
        self.lblWelcome_Title.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:20pt;\">Welcome!</span></p></body></html>", None))
        self.lblWelcome_Message.setText(_translate("UIView", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Welcome to PMConverter!</span></p></body></html>", None))
        self.cmdStep0_Start.setText(_translate("UIView", "Start", None))
        self.lblStep1_Title.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:20pt;\">Step 1: Select a file...</span></p></body></html>", None))
        self.lblStep1_InputFile.setText(_translate("UIView", "I want to convert:", None))
        self.btnStep1_InputFile.setText(_translate("UIView", "File...", None))
        self.lblStep1_InputFormat.setText(_translate("UIView", "From:", None))
        self.lblStep1_OutputFormat.setText(_translate("UIView", "To:", None))
        self.chkStep1_ExcelExtendedVersion.setText(_translate("UIView", "Extended version", None))
        self.cmdStep1_Next.setText(_translate("UIView", "Next", None))
        self.lblStep2_Title.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:20pt;\">Step 2: add visualisations</span></p></body></html>", None))
        self.btnStep2_ImportSettings.setText(_translate("UIView", "Import", None))
        self.btnStep2_ExportSettings.setText(_translate("UIView", "Export", None))
        self.grpbxStep2_VisualisationDescription.setTitle(_translate("UIView", "Title of the chosen visualisation", None))
        self.lblStep2_VisualisationDescription.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:10pt;\">Description of the chosen visualisation</span></p></body></html>", None))
        self.grpbxStep2_VisualisationParameters.setTitle(_translate("UIView", "Parameters", None))
        self.lblStep2_Param_NoParams.setText(_translate("UIView", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">No parameters to show</span></p></body></html>", None))
        self.lblStep2_Param_LevelOfDetail.setText(_translate("UIView", "Level of detail: ", None))
        self.chkStep2_Param_RelativeValues.setText(_translate("UIView", "Use relative values", None))
        self.chkStep2_Param_AddThreshold.setText(_translate("UIView", "Add threshold to data", None))
        self.lblStep2_Param_StartingThreshold.setText(_translate("UIView", "Threshold start value: ", None))
        self.lblStep2_Param_EndingThreshold.setText(_translate("UIView", "Threshold end value: ", None))
        self.lblStep2_ParamsSaved.setText(_translate("UIView", "Saved changes", None))
        self.btnStep2_AddVisualisation.setText(_translate("UIView", "Add", None))
        self.btnStep2_DeleteVisualisation.setText(_translate("UIView", "Delete", None))
        self.cmdStep2_Convert.setText(_translate("UIView", "Convert", None))
        self.lblConverting_Title.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:20pt;\">Converting...</span></p></body></html>", None))
        self.lblConverting_Message.setText(_translate("UIView", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">We are converting your file!</span></p><p align=\"center\"><span style=\" font-size:16pt;\"><br/></span></p><p align=\"center\"><span style=\" font-size:16pt;\">Please wait a moment...</span></p></body></html>", None))
        self.lblConverting_WaitingSpinner.setText(_translate("UIView", "[WAITING]", None))
        self.lblConvertingError_Title.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:20pt;\">Conversion failed</span></p></body></html>", None))
        self.lblFinished_Title.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:20pt;\">Done...</span></p></body></html>", None))
        self.lblFinished_Message.setText(_translate("UIView", "<html><head/><body><p><span style=\" font-size:16pt;\">Your file is saved to:</span></p></body></html>", None))
        self.lblFinished_OutputFilename.setText(_translate("UIView", "<html><head/><body><p>[output filename]</p></body></html>", None))
        self.cmdFinished_End.setText(_translate("UIView", "Exit", None))

from customWidgets.custom_QComboBox import Custom_QComboBox
